{% set name = "jupysql" %}
{% set version = "0.7.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupysql-{{ version }}.tar.gz
  sha256: 99b333a11519a9006ad8d8f4e5ac233e7e52bee4811a34295cd8714c8b56e50b

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - psutil
    - python >=3.7
    - prettytable
    - ipython >=1.0
    - sqlalchemy
    - sqlparse
    - ipython_genutils >=0.1.0
    - sqlglot
    - jinja2
    - ploomber-core >=0.2.7
    - importlib-metadata

test:
  imports:
    - sql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ploomber/jupysql
  summary: Better SQL in Jupyter
  dev_url: https://github.com/ploomber/jupysql
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yafimvo
    - idomic
    - edublancas
    - sterlinm
