{% set name = "jupysql" %}
{% set version = "0.10.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupysql-{{ version }}.tar.gz
  sha256: 93100c0c2cf30d7ec679135fab030a7f955991c6adfb38eb8534f5e1274d3348

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - ploomber-extension
    - jupysql-plugin >=0.4.2
    - psutil
    - python >=3.7
    - prettytable >=3.12.0
    - ipython >=1.0
    - sqlalchemy
    - sqlparse
    - ipython_genutils >=0.1.0
    - sqlglot >=11.3.7
    - jinja2
    - ploomber-core >=0.2.7
    - importlib-metadata

test:
  imports:
    - sql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ploomber/jupysql
  summary: Better SQL in Jupyter
  dev_url: https://github.com/ploomber/jupysql
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yafimvo
    - idomic
    - edublancas
    - sterlinm
    - neelasha23
